# Generated by Django 5.0.4 on 2024-05-10 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu_group",
            old_name="description",
            new_name="name",
        ),
    ]
