# Generated by Django 5.0.4 on 2024-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_description_menu_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Open"), (2, "Closed"), (3, "Under Maintenance")],
                default=2,
            ),
        ),
    ]
