# Generated by Django 5.0.4 on 2024-05-13 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_restaurant_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="logo",
            new_name="logo_image_url",
        ),
        migrations.RenameField(
            model_name="restaurant",
            old_name="representative_menu_picture",
            new_name="representative_menu_image",
        ),
    ]
