# Generated by Django 5.0.4 on 2024-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_logo_restaurant_logo_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_group',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
    ]
