# Generated by Django 5.0.6 on 2024-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_option_group_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option_group',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
