# Generated by Django 5.0.4 on 2024-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_alter_category_category_alter_hashtag_hashtag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (210001, "Available"),
                    (210002, "Sold out"),
                    (210003, "Hedden"),
                    (210999, "Modified or Deleted"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (200000, "Shut down"),
                    (200001, "Open"),
                    (200002, "Prepare"),
                    (200003, "Close"),
                ],
                default=200003,
            ),
        ),
    ]
