# Generated by Django 5.0.4 on 2024-05-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_alter_category_category_alter_hashtag_hashtag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (210001, "판매중"),
                    (210002, "품절"),
                    (210003, "숨김"),
                    (210999, "변경 또는 삭제"),
                ],
                default=210001,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (200000, "Shut Down"),
                    (200001, "Open"),
                    (200002, "Closed"),
                    (200003, "Under Maintenance"),
                ],
                default=200002,
            ),
        ),
    ]
