# Generated by Django 5.0.6 on 2024-05-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menu_description_alter_menu_status_and_more'),
        ('restaurant', '0007_alter_menu_status_alter_restaurant_status'),
    ]

    operations = [
    ]
