# Generated by Django 5.0.6 on 2024-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
