# Generated by Django 5.0.6 on 2024-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_fee_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_option',
            name='option_group_name',
            field=models.CharField(max_length=50),
        ),
    ]
