# Generated by Django 5.0.6 on 2024-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delivery_fee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_fee_info',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
