# Generated by Django 5.0.4 on 2024-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_delivery_fee_info_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="delivery_pay",
            new_name="delivery_fee",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_method",
            new_name="method",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="final_price",
            new_name="order_price",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_time",
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="PMS001", max_length=6),
        ),
    ]
