# Generated by Django 5.0.4 on 2024-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_rename_delivery_pay_payment_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="PMS000", max_length=6),
        ),
    ]
