# Generated by Django 5.0.6 on 2024-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cooking_time",
            field=models.DateTimeField(null=True),
        ),
    ]
