# Generated by Django 5.0.6 on 2024-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="completion_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="estimated_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
