# Generated by Django 5.0.6 on 2024-05-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_delivery_delivery_man"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="failure_reason",
            new_name="cancle_reason",
        ),
        migrations.AddField(
            model_name="delivery",
            name="cancle_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_status",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_self_delivery",
            field=models.BooleanField(default=0),
        ),
    ]
