# Generated by Django 5.0.6 on 2024-05-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_rename_failure_reason_payment_cancle_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="cancle_reason",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
