# Generated by Django 5.0.6 on 2024-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_payment_cancle_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="cancle_reason",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
