# Generated by Django 5.0.4 on 2024-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_payment_cancle_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="dispatch_status",
        ),
        migrations.AlterField(
            model_name="payment",
            name="cancle_reason",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveIntegerField(default=310000),
        ),
    ]
