# Generated by Django 5.0.6 on 2024-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_remove_order_dispatch_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_status",
            field=models.PositiveIntegerField(
                choices=[
                    (320000, "Dispatch pending"),
                    (320001, "Pickup pending"),
                    (320002, "Delivering"),
                    (320003, "Completed"),
                ],
                default=320000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cancle_reason",
            field=models.PositiveIntegerField(
                choices=[
                    (200000, "Restaurant shutdown"),
                    (200002, "Restaurant prepare"),
                    (200003, "Restaurant close"),
                    (210002, "Menu option sold out"),
                    (210003, "Menu option hidden"),
                    (210999, "Menu option modified or deleted"),
                    (300995, "Customer request"),
                    (300996, "Wrong address"),
                    (300997, "Restaurant issue"),
                    (300998, "Out of stock"),
                    (300999, "Closed"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.PositiveIntegerField(
                choices=[
                    (310000, "Payment pending"),
                    (310001, "Payment success"),
                    (310002, "Payment failed"),
                    (310003, "Payment cancel"),
                    (300000, "Order pending"),
                    (300001, "Order accepted"),
                    (300002, "Order rejected"),
                    (300091, "Order cancelled by store"),
                    (300092, "Order cancelled by customer"),
                    (300101, "Cooking"),
                    (300102, "Cooking complete"),
                    (320000, "Delivery dispatch pending"),
                    (320001, "Delivery pickup pending"),
                    (320002, "Delivery in progress"),
                    (320003, "Delivery completed"),
                ],
                default=310000,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cancle_reason",
            field=models.PositiveIntegerField(
                choices=[
                    (310400, "Invalid card info"),
                    (310410, "Insufficient balance"),
                    (310500, "Server internal error"),
                    (310502, "Communication error"),
                    (310600, "Order cancelled"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (310101, "Online - card"),
                    (310102, "Online - cash"),
                    (310201, "Offline - card"),
                    (310202, "Offline - cash"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (310000, "Payment pending"),
                    (310001, "Payment successful"),
                    (310002, "Payment failed"),
                    (310003, "Payment cancelled"),
                    (310010, "Payment offline"),
                ],
                default=310000,
            ),
        ),
    ]
