# Generated by Django 5.0.4 on 2024-05-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='represent',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(default=None, null=True),
        ),
    ]
