# Generated by Django 5.0.4 on 2024-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_represent_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_group',
            name='option_name',
            field=models.CharField(default='sauce', max_length=20),
        ),
    ]
