# Generated by Django 5.0.4 on 2024-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_option_group_option_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='menu_group',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='option',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='option_group',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='option_group_to_menu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='restaurantcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='restauranthashtag',
            name='deleted_at',
        ),
    ]
