# Generated by Django 5.0.4 on 2024-04-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
