# Generated by Django 5.0.4 on 2024-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_adress_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(default="home", max_length=50),
        ),
    ]
