# Generated by Django 5.0.4 on 2024-05-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery_man",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivery_man_name", models.CharField(max_length=255)),
                ("delivery_type", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_status",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Order received"),
                            (1, "Cooking"),
                            (2, "Cooking complete"),
                        ]
                    ),
                ),
                ("cooking_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("delivery_address", models.CharField(max_length=255)),
                ("dispatch_status", models.IntegerField(default=None, null=True)),
                ("store_request", models.TextField(default=None, null=True)),
                ("rider_request", models.TextField(default=None, null=True)),
                ("total_price", models.PositiveIntegerField(default=None, null=True)),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("cancle_reason", models.TextField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order_option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option_name", models.CharField(max_length=255)),
                ("option_price", models.PositiveIntegerField(default=None, null=True)),
                ("option_group_name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_method", models.CharField(max_length=255)),
                ("payment_time", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.PositiveIntegerField(default=None, null=True)),
                ("coupon", models.PositiveIntegerField(default=None, null=True)),
                ("delivery_pay", models.PositiveIntegerField(default=None, null=True)),
                ("final_price", models.PositiveIntegerField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("estimated_time", models.DateTimeField()),
                ("completion_time", models.DateTimeField()),
                (
                    "delivery_man",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.delivery_man",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
