# Generated by Django 5.0.4 on 2024-05-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_estunated_time_delivery_estimated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='delivery_man',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order_option',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order_option_group',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_name', to='order.order'),
        ),
    ]
